ISID and MAC Filter Creation
boucadair/enhanced-acl-netmod pull request #17
Opened 2023-02-21 08:55 UTC by sbarguil

Innitial Commit #4

2023-03-06 13:08 UTC, sbarguil commented
@sbarguil To include Features in the YANG for bth filtering options.

2023-03-07 15:50 UTC, boucadair requested changes

2023-03-07 15:50 UTC, boucadair commented on yang/ietf-acl-enh.yang
> +  feature match-on-vlan-flter {
```suggestion
  feature match-on-vlan-filter {

```

2023-03-07 15:50 UTC, boucadair commented on yang/ietf-acl-enh.yang
> +      if-feature "match-on-vlan-flter";
```suggestion
      if-feature "match-on-vlan-filter";

```

2023-03-07 15:50 UTC, boucadair commented on yang/ietf-acl-enh.yang
> +        "Indicates how to handle MAC VLAN.";
```suggestion
        "Indicates how to handle MAC VLANs.";

```

2023-03-07 15:50 UTC, boucadair commented on draft-ietf-netmod-acl-extensions.md
> +802.1ah standard. However, instead of multiplexing VLANs, PBB
Can we add a reference? Thanks.

2023-03-07 15:50 UTC, boucadair commented on draft-ietf-netmod-acl-extensions.md
> +Beign able to filter by I-Component Service identifier is a feature of
```suggestion
Being able to filter by I-component Service identifier is a feature of
```

2023-03-07 15:50 UTC, boucadair commented on draft-ietf-netmod-acl-extensions.md
> +requirements. So, all packets that are bridged within a VLAN or that
Any pointer to cite here?

2023-03-10 12:47 UTC, merged